# Generated by Django 5.2.1 on 2025-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_equipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
