# Generated by Django 5.2.1 on 2025-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_corrida_foto_pista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='numero',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='posicao',
            field=models.PositiveIntegerField(),
        ),
    ]
