# Generated by Django 5.2.1 on 2025-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_resultado_equipe_remove_resultado_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
