# Generated by Django 5.2.1 on 2025-06-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_equipe_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='bandeira',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='foto_pista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
