# Generated by Django 5.2.1 on 2025-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
