# Generated by Django 5.2.1 on 2025-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equipe_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
