# Generated by Django 5.2.1 on 2025-06-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_equipe_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='pista',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resultado',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipe'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='numero',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piloto'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='posicao',
            field=models.IntegerField(),
        ),
    ]
