# Generated by Django 5.2.1 on 2025-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_resultado_piloto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrida',
            name='descricao',
        ),
        migrations.AddField(
            model_name='corrida',
            name='bandeira',
            field=models.ImageField(blank=True, null=True, upload_to='bandeiras/'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='pista',
            field=models.TextField(),
        ),
    ]
