# Generated by Django 5.2.1 on 2025-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_corrida_descricao_corrida_bandeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
    ]
