# Generated by Django 5.2.1 on 2025-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_corrida_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='foto_pista',
            field=models.ImageField(blank=True, null=True, upload_to='pistas/'),
        ),
    ]
