# Generated by Django 5.2.1 on 2025-05-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotos', to='core.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.corrida')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piloto')),
            ],
            options={
                'unique_together': {('corrida', 'piloto')},
            },
        ),
    ]
