# Generated by Django 5.2.1 on 2025-05-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.piloto'),
        ),
    ]
