# Generated by Django 5.2.1 on 2025-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_equipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='cor',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
    ]
