# Generated by Django 5.2.1 on 2025-06-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_corrida_descricao_corrida_pista_resultado_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.piloto'),
        ),
    ]
